package core;

public enum Header {
	M_ID(-1), M_NOMEINVALIDO(-1), M_LISTAJOGOS(-1), M_ESCOLHAJOGO(-1), M_AGUARDANDO(-1), M_OPONENTEDISP(-1), M_PROMPTRETOMAR(-1), M_RETOMAR(-1),
	
	M_BATALHANAVAL_BUILDPROMPT(0), M_BATALHANAVAL_BUILDACTION(0), M_BATALHANAVAL_WAIT(0), M_BATALHANAVAL_BEGINTURN(0), M_BATALHANAVAL_OPTURN(0), M_BATALHANAVAL_ATTACKACTION(0), M_BATALHANAVAL_END(0),
	M_FORCA_END(1), M_FORCA_BEGINTURN(1), M_FORCA_OPTURN(1), M_FORCA_GUESS(1);
	
	private int jogo;
	private Header(int v) {
		jogo = v;
	}
	
	public int getJogo() {
		return jogo;
	}
	
}
